from AccGenBot import BotzCity
from telethon import events, Button
import random
from AccGenBot.func import check 
from vars import var

USERNAME = var.CHANNEL_USERNAME
CHANNEL = var.CHANNEL_URL

bot = BotzCity

@bot.on(events.NewMessage(pattern="/netflix"))
async def _(event):
   join = [[Button.url("Jᴏɪɴ ᴄʜᴀɴɴᴇʟ", f"{CHANNEL}")]]
   lol = await check(USERNAME, event, bot)
   username = f"@{event.sender.username}" if username else event.sender.first_name
   if lol is False:
       await event.reply(f"**Heya {event.sender.first_name}, join my channel to use me!**", buttons=join)
       return
   gen = await event.reply("`Generating Account Pls weit`")
   with open("netflix.txt") as Alain:
       noice = Alain.read().splitlines()
       nice = random.choice(noice)
       email, pass = nice.split(":")
   okay = f"""**Account Generated Successfully**"
**Type:** `Netflix`
**Combo:** `{email}`:`{pass}`
**Email:** **{email}**
**Password:** `{pass}`

**Generated by:** {username}"""
   await gen.edit(okay)
